package com.project.report_service.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// Note: java.util.List is not needed here as productsSupplied is a Long count
// import java.util.List;

@Data // Lombok annotation for Getters, Setters, toString, equals, hashCode
@NoArgsConstructor // Lombok annotation for no-arg constructor
@AllArgsConstructor // Lombok annotation for all-arg constructor
public class SupplierReportDto {
    private Long supplierId;
    private String supplierName;
    private Long productsSupplied; // This field should be Long to store the count
    private Long totalQuantitySupplied;

    // Getters and Setters are generated by Lombok's @Data
}
